/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_gwj_mfmod_MFmod */

#ifndef _Included_dev_gwj_mfmod_MFmod
#define _Included_dev_gwj_mfmod_MFmod
#ifdef __cplusplus
extern "C" {
#endif

#include <android/log.h>
#define LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,"fmodutil-jni", __VA_ARGS__)



/*
 * Class:     dev_gwj_mfmod_MFmod
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_gwj_mfmod_MFmod_init
  (JNIEnv *, jobject);

/*
 * Class:     dev_gwj_mfmod_MFmod
 * Method:    playSound
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dev_gwj_mfmod_MFmod_playSound
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dev_gwj_mfmod_MFmod
 * Method:    onFmodEvent1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_gwj_mfmod_MFmod_onFmodEvent1
  (JNIEnv *, jobject);

/*
 * Class:     dev_gwj_mfmod_MFmod
 * Method:    onFmodEvent2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_gwj_mfmod_MFmod_onFmodEvent2
  (JNIEnv *, jobject);

bool cheeckResult(FMOD_RESULT result);

#ifdef __cplusplus
}
#endif
#endif
